package com.example.jdbc.mapper;

import com.example.jdbc.model.ToDo;
import org.apache.ibatis.annotations.Select;

import java.util.Date;
import java.util.List;

public interface ToDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table to_do
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table to_do
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    int insert(ToDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table to_do
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    int insertSelective(ToDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table to_do
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    ToDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table to_do
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    int updateByPrimaryKeySelective(ToDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table to_do
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    int updateByPrimaryKey(ToDo record);

    /**
     * 通过创建者查询待办事项列表
     * @param creator
     * @return
     */
    List<ToDo> selectByCreator(String creator);

    @Select("select * from to_do where id=1")
    List<ToDo> selectByAnnotation(Date startTime, Date endTime);
}