package com.example.jdbc.model;

import java.util.Date;

public class ToDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.id
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.gmt_create
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.gmt_modified
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.creator
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.modifier
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.is_deleted
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.status
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.content
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column to_do.type
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.id
     *
     * @return the value of to_do.id
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.id
     *
     * @param id the value for to_do.id
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.gmt_create
     *
     * @return the value of to_do.gmt_create
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.gmt_create
     *
     * @param gmtCreate the value for to_do.gmt_create
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.gmt_modified
     *
     * @return the value of to_do.gmt_modified
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.gmt_modified
     *
     * @param gmtModified the value for to_do.gmt_modified
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.creator
     *
     * @return the value of to_do.creator
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.creator
     *
     * @param creator the value for to_do.creator
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.modifier
     *
     * @return the value of to_do.modifier
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.modifier
     *
     * @param modifier the value for to_do.modifier
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.is_deleted
     *
     * @return the value of to_do.is_deleted
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.is_deleted
     *
     * @param isDeleted the value for to_do.is_deleted
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.status
     *
     * @return the value of to_do.status
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.status
     *
     * @param status the value for to_do.status
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.content
     *
     * @return the value of to_do.content
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.content
     *
     * @param content the value for to_do.content
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column to_do.type
     *
     * @return the value of to_do.type
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column to_do.type
     *
     * @param type the value for to_do.type
     *
     * @mbggenerated Fri Jul 08 18:49:19 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}